"""pm25 readings

Revision ID: 15d5df44d22f
Revises: 8efd356df197
Create Date: 2026-07-20 10:08:02.119321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d5df44d22f'
down_revision: Union[str, None] = '8efd356df197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pm25_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=20), nullable=False),
    sa.Column('station_name_th', sa.String(length=200), nullable=False),
    sa.Column('station_name_en', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pm25_value', sa.Float(), nullable=True),
    sa.Column('pm25_aqi', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'observed_at', name='uq_pm25_readings_station_observed')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pm25_readings')
    # ### end Alembic commands ###
