"""exchange rates

Revision ID: 27ca9594dbaa
Revises: f8a588bf0e12
Create Date: 2026-07-20 14:11:52.874422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ca9594dbaa'
down_revision: Union[str, None] = 'f8a588bf0e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('currency_name_th', sa.String(length=200), nullable=False),
    sa.Column('currency_name_en', sa.String(length=200), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('buying_sight', sa.Float(), nullable=True),
    sa.Column('buying_transfer', sa.Float(), nullable=True),
    sa.Column('selling', sa.Float(), nullable=True),
    sa.Column('mid_rate', sa.Float(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_code', 'rate_date', name='uq_exchange_rates_currency_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
