"""weather forecasts

Revision ID: f8a588bf0e12
Revises: 15d5df44d22f
Create Date: 2026-07-20 11:39:34.088397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a588bf0e12'
down_revision: Union[str, None] = '15d5df44d22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province_code', sa.Integer(), nullable=False),
    sa.Column('province_name_th', sa.String(length=120), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('cond', sa.Integer(), nullable=True),
    sa.Column('tc_max', sa.Float(), nullable=True),
    sa.Column('tc_min', sa.Float(), nullable=True),
    sa.Column('rh', sa.Float(), nullable=True),
    sa.Column('rain', sa.Float(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('province_code', 'forecast_date', name='uq_weather_forecasts_province_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_forecasts')
    # ### end Alembic commands ###
